name: Build and Publish WASM Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test

    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: latest

    - name: Build with wasm-pack
      run: wasm-pack build --release --target bundler

    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish to npm
      if: github.event_name == 'release' && github.event.action == 'published'
      run: wasm-pack publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - uses: actions/upload-artifact@v4
      with:
        name: wasm-package
        path: pkg/
